apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: radio-recorder
build:
  artifacts:
  - image: radio-recorder
    jib: {
      type: gradle
    }
  # local:
  #   skipPush: true
deploy:
  kubectl:
    manifests:
    - k8s/nhk-recorder.yaml
