apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: radio-recorder
build:
  artifacts:
  - image: radio-recorder ### YOUR_IMAGE_NAME
    context: ./
    docker:
      dockerfile: manifests/docker/Dockerfile.graalvm11
  tagPolicy:
    sha256: {}
  local:
    push: true
deploy:
  kubectl:
    manifests:
    - manifests/k8s/nhk-english0.yaml
    - manifests/k8s/nhk-english2.yaml
    - manifests/k8s/nhk-english3.yaml
